update to clear shit up
Dot-Stuff/flxanimate pull request #20
Opened 2022-11-02 23:56 UTC by Zoardedz

2022-11-03 00:02 UTC, MemeHoovy approved these changes

2022-11-03 00:15 UTC, TheKitBoi approved these changes

2022-11-03 18:07 UTC, ACrazyTown commented
Is `character.updateAnimation()` necessary? Iirc it worked fine for me without it

2022-11-03 18:19 UTC, Cheemsandfriends commented
`character.updateAnimation()` doesn't need to be called, it's something that FlxSprite already uses.
The only thing you could say I'm doing is just replacing the animation handlers.
Why does it not work for you? Are you using a class extending `FlxAnimate` and overriding update without adding `super.update()`?
that would be my guess

2022-11-03 18:56 UTC, Zoardedz commented
im not extending flxanimate, the updateAnimation function was necessary for me because it didn't play the animation

2022-11-04 00:17 UTC, TheKitBoi requested changes

2022-11-04 00:17 UTC, TheKitBoi commented on README.md
> +To actually let the animation update go to the update function and do:
you should add the (optional)

2022-11-04 18:13 UTC, Zoardedz commented on README.md
> +To actually let the animation update go to the update function and do:
mk

2022-11-04 18:17 UTC, Zoardedz commented
i made a file which basically prevents it from doing this, it just gets a spriteatlas group then pushes itself to that group, you can for loop in the update function on each spriteatlas in the current state you're in and by that i dont mean the spriteatlas itself and do the update function for it 
[SpriteAtlas.txt](https://github.com/Dot-Stuff/flxanimate/files/9941050/SpriteAtlas.txt)

2022-11-07 15:37 UTC, ACrazyTown commented
> i made a file which basically prevents it from doing this, it just gets a spriteatlas group then pushes itself to that group, you can for loop in the update function on each spriteatlas in the current state you're in and by that i dont mean the spriteatlas itself and do the update function for it [SpriteAtlas.txt](https://github.com/Dot-Stuff/flxanimate/files/9941050/SpriteAtlas.txt)

But the thing is that this shouldn't happen at all. `updateAnimation()` should not be needed to be called, I have never needed to call it and I've been using FlxAnimate since like early 2022.

How do you intialise FlxAnimate? Are you sure you don't set `active` to false or something?

2022-11-10 21:10 UTC, Zoardedz commented
yes i'm sure of all of that.

2022-11-16 20:11 UTC, Cheemsandfriends commented
I really can not merge this pull request, since this isn't what a dev who wants to implement FlxAnimate that doesn't want to touch much about the source code has to add nowhere.
`updateAnimation()` is an FlxSprite function that is already been called in [`update()`](https://github.com/HaxeFlixel/flixel/blob/05b41665697e54f6571e0452ad6b5480ebf01df5/flixel/FlxSprite.hx#L751). The only thing that FlxAnimate does to redirect the animation handler is overriding the function and call the update function of the animation handler in there.
But I do wanna know why you're having this issue, that's been bothering me for a while.

2022-11-16 23:08 UTC, Zoardedz commented
i honestly don't know but close this pull request if you want, if somebody else is having this problem i'll see if i can help

2022-11-16 23:08 UTC, closed without merging